'''capture_full_schema_v0.6.0

Revision ID: 2028602367ca
Revises: 2f01db1168f5
Create Date: 2026-07-09 18:15:05.128923
'''
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2028602367ca'
down_revision: Union[str, Sequence[str], None] = '2f01db1168f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'layer',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'working'::character varying"))
    op.alter_column('memories', 'decay_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('memories', 'access_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'access_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('memories', 'decay_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('memories', 'layer',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'working'::character varying"))
    # ### end Alembic commands ###
