'''create events table with payload JSONB

Revision ID: 2f01db1168f5
Revises: 
Create Date: 2026-07-08 01:55:31.061902
'''
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2f01db1168f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
